name: Build all files to test building
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-versions: ["3.8"]

            steps:
                - uses: actions/checkout@v3
                - name: Set up Python ${{ matrix.python-version }}
                  uses: actions/setup-python@v4
                  with:
                      python-version: ${{ matrix.python-version }}
                - name: Install dependencies
                  run: |
                      python -m pip install --update pip wheel
                      pip install -r requirements.txt
                - name: Build
                  run: |
                      bin/lektor build -f webpack

